### ISSUE TITLE
I want to use my public key for encryption? Can I do this?

### ISSUE THREAD

**Issue by pravin-mindstix** [m1ga/ti-crypt#1]
I am new to appcelerator, I want to Encrypt data using my public key and decrypt using private key.

I have publicKey.pem how can I use this in this module?

**Comment by blacktiago** [comment]
You must remove the begin and end tags of the .pem form your server like this en java for instance:
```
public static PublicKey loadPublicKey() throws Exception {

    String publicKeyPEM = FileUtils.readFileToString(new File("publickey.pem"), StandardCharsets.UTF_8);

    publicKeyPEM = publicKeyPEM
            .replace("-----BEGIN PUBLIC KEY-----", "")
            .replace("-----END PUBLIC KEY-----", "")
            .replaceAll("\\s", "");
    byte[] publicKeyDER = Base64.getDecoder().decode(publicKeyPEM);
    KeyFactory keyFactory = KeyFactory.getInstance("RSA");
    PublicKey publicKey = keyFactory.generatePublic(new X509EncodedKeySpec(publicKeyDER));
    
return publicKey;
}
```
more details [here](https://adangel.org/2016/08/29/openssl-rsa-java/)

When you get the clean key you could use the library the same way the example does but witout generating the key:

`
var miPublicKey = someKindOfJsonResponse.publicKey;
var crypt = require("miga.ticrypt");
var plainData = crypt.encode({plainText: 'text to process', publicKey: miPublicKey});
`
